import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Danh sách bài viết",
    description: "Generated by create next app",
  };
export default function page() {
  return (
    <div>
      <b>Danh sách bài viết</b>
    </div>
  )
}
